#!/usr/bin/env bash

# Copyright 2016 Luis Veliz
# <a href="mailto:l.veliz@live.com>Enviar Correo</a>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $( echo $EUID ) -ne 0 ]; then
    echo 'Necesitas ejecutar el script como superusuario'; exit 1
fi

if ! git --version &> /dev/null; then
    echo 'Necesitas instalar Git para continuar'; exit 1
fi

if ! stow --version &> /dev/null; then
    echo 'Necesitas instalar Stow para continuar'; exit 1
fi

[ -e ~/.vim ] && (rm -rf ~/.vim.bak; mv ~/.vim ~/.vim.bak) 
[ -e ~/.vimrc ] && (rm -rf ~/.vimrc.bak; mv ~/.vimrc ~/.vimrc.bak) 
[ -e ~/.bashrc ] && (rm -rf ~/.bashrc.bak; mv ~/.bashrc ~/.bashrc.bak) 
[ -e ~/.tmux.conf ] && (rm -rf ~/.tmux.conf.bak; mv ~/.tmux.conf ~/.tmux.conf.bak) 

git clone https://github.com/luisvma/dotfiles.git
cd dotfiles; stow -vt ~/ vim git tmux bash

