#!/usr/bin/env bash

# Copyright 2016 Luis Veliz
# <a href="mailto:l.veliz@live.com>Enviar Correo</a>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $( echo $EUID ) -ne 0 ]; then
    echo 'Necesitas ejecutar el script como superusuario'; exit 1
fi

yaourt -S --noconfirm java etcher glassfish-v4
pacman -S --noconfirm vim gvim git eclipse mariadb postrgresql php apache-php apache stow downgrader

